import csv

import pandas
from django.core.management import BaseCommand
from django.db.models import Q

from chemical.models import *


class Command(BaseCommand):

    def handle(self, *args, **options):
        for key, value in organism_list.items():
            Organism.objects.filter(latin_name=key).update(english_name=value)


organism_list = {
"Abramis brama":"Fish",
"Anguilla japonica":"Eel",
"Oreochromis niloticus":"Fish",
"Oryctolagus cuniculus":"Rabbit",
"Pusa sibirica":"Seal",
"Phalacrocorax carbo":"Bird",
"Macaca mulatta":"Monkey",
"Coturnix japonica":"Bird",
"Poeciliopsis lucida":"Fish",
"Abramis brama":"Fish",
"Acanthopagrus schlegelii":"Fish",
"Achatina fulica":"Snails",
"Acipenser brevirostrum":"Fish",
"Acipenser oxyrinchus oxyrinchus":"Fish",
"Acipenser sinensis":" Fish",
"Aedes aegypti":"Mosquito",
"Aedes albopictus":"Mosquito",
"Agelena labyrinthica":"Spiders",
"Alburnus alburnus":"Fish",
"Alligator mississippiensis":"Alligators",
"Ameiurus nebulosus":"Fish",
"Anabas testudineus":"Fish",
"Anas":"Bird",
"Anas platyrhynchos":"Duck",
"Andrias japonicas":"Salamander",
"Anguilla":"Eel",
"Anolis carolinensis":"Lizard",
"Anopheles albimanus":"Mosquito",
"Anopheles gambiae":"Mosquito",
"Anopheles quadrimaculatus":"Mosquito",
"Anopheles stephensi":"Mosquito",
"Anopheles quadrimaculatus":"Mosquito",
"Anopheles stephensi":"Mosquito",
"Aphanius iberus":"Fish",
"Aphis glycines":"Insects",
"Aphis gossypii":"Insects",
"Apis cerana cerana":"Bees",
"Apis mellifera":"Bees",
"Aplysia californica":"Slugs",
"Aplysia kurodai":"Slugs",
"Apolygus lucorum":"Bugs",
"Arctica islandica":"Clams",
"Argopecten purpuratus":"Scallops",
"Arvicolinae":"Rodents",
"Asterias rubens":"Starfish",
"Atrachya menetriesi":"Beetles",
"Azumapecten farreri":"Crustaceans",
"Bactrocera oleae":"Flies",
"Ballerus ballerus":"Fish",
"Barbus graellsii":"Fish",
"Bathymodiolus azoricus":"Clams",
"Bemisia tabacia":"Flies",
"Biomphalaria glabrata":"Snails",
"Blarina brevicauda":"Shrew",
"Blattella germanica":"Cockroaches",
"Blattodea":"Cockroaches",
"Blicca bjoerkna":"Fish",
"Boaedon fuliginosus":"Snakes",
"Boleophthalmus pectinirostris":"Fish",
"Bombus ignitus":"Bee",
"Bombyx mori":"Worm",
"Boreogadus saida":"Fish",
"Bos taurus":"Cows",
"Bovinae":"Cows",
"Brachionus sp. 'koreanus'":"Aquatic animal",
"Brugia malayi":"Worms",
"Brycon cephalus":"Fish",
"Bubalus bubalis":"Buffalo",
"Bufo bufo":"Toads",
"Bungarus":"Snakes",
"Bursaphelenchus xylophilus":"Worms",
"Caenorhabditis elegans":"Worms",
"Caiman latirostris":"Crocodiles",
"Calanus finmarchicus":"Plankton",
"Caligus rogercresseyi":"Lice",
"Callinectes sapidus":"Crabs",
"Callithrix jacchus":"Primates",
"Callitrichidae":"Primates",
"Cambarellus montezumae":"Fish",
"Camelus":"Camels",
"Camelus dromedarius":"Camels",
"Campostoma oligolepis":"Fish",
"Canis lupus familiaris":"Dogs",
"Canis lupus":"Dogs",
"Capra":"Goats",
"Capra hircus":"Goats",
"Carangoides":"Fish",
"Carassius auratus":"Fish",
"Carassius cuvieri":"Fish",
"Carassius gibelio":"Fish",
"Carduelis chloris":"Birds",
"Catla catla":"Fish",
"Catostomus macrocheilus":" Fish",
"Cavia porcellus":"Guinea Pigs",
"Cebus capucinus":"Monkeys",
"Cerastoderma edule":"Clams",
"Ceratitis capitata":"Flies",
"Cervus elaphus":"Deer",
"Chamelea gallina":"Clams",
"Channa punctata":"Fish",
"Channa striata":"Fish",
"Chelon labrosus":"Fish",
"Chilo suppressalis":"Insects",
"Chinchilla chinchilla":"Rodents",
"Chironomus riparius":"Insects",
"Chlorocebus aethiops":"Monkeys",
"Chrysemys picta bellii":"Turtles",
"Ciconia ciconia":"Birds",
"Cimex lectularius":"Bed bugs",
"Ciona intestinalis":"Sea squirt",
"Cirrhinus mrigala":"Fish",
"Clarias batrachus":"Fish",
"Clarias gariepinus":"Fish ",
"Clonorchis sinensis":"Worms",
"Cochliomyia hominivorax":"Insects",
"Colinus virginianus":"Birds",
"Collembola":"hexapoda",
"Colossoma macropomum":"fish",
"Columba livia":"pigeons",
"Columbidae":"pigeons",
"Corbicula fluminea":"clams",
"Coregonus albula":"fish",
"Coris julis":"fish",
"Corvus macrorhynchos":"birds",
"Cotesia vestalis":"wasps",
"Cottus gobio":"fish",
"Coturnix":"birds",
"Coturnix coturnix":"quails",
"Coturnix japonica":"quails",
"Crassostrea gigas":"oysters",
"Crassostrea virginica":"oysters",
"Cricetinae":"Hamsters",
"Cricetulus griseus":"Hamsters",
"Ctenocephalides felis":"fleas",
"Ctenopharyngodon idella":"fish",
"Culex pipiens":"mosquitos",
"Cyanistes caeruleus":"birds",
"Cydia pomonella":"mothes",
"Cynoglossus semilaevis":"fish",
"Cynops orientalis":"newts",
"Cynoscion nebulosus":"fish",
"Cyprinodon variegatus":"fish",
"Daphnia magna":"crustaceans",
"Delphinapterus leucas":"whales",
"Diaeretiella rapae":"insects",
"Dicentrarchus labrax":"Fish",
"Didelphidae":"Possums",
"Dreissena polymorpha":"Mussels",
"Drosophila melanogaster":"Flies",
"Drosophila simulans":"Flies",
"Dugesia japonica":"triclads",
"Echinococcus granulosus":"tapeworms",
"Echinoidea":"sea urchins",
"Eisenia Andrei":"worms",
"Eisenia fetida":"worms",
"Electrophorus electricus":"eels",
"Enchytraeus albidus":"worms",
"Eobania vermiculata":"snails",
"Epinephelus coioides":"fish",
"Equus caballus":"horses",
"Eriocheir sinensis":"crabs",
"Erythrocebus patas":"monkeys",
"Esox Lucius":"fish",
"Euphlyctis cyanophlyctis":"frogs",
"Exorista sorbillans":"flies",
"Falco sparverius":"birds",
"Felis catus":"cats",
"Fenneropenaeus chinensis":"shrimp",
"Fenneropenaeus indicus":"prawn",
"Folsomia candida":"hexapods",
"Frankliniella occidentalis":"thrips ",
"Fundulus grandis":"fish",
"Fundulus heteroclitus":"fish",
"Fundulus lima":"fish",
"Gadus morhua":"fish",
"Gallotia galloti":"reptile",
"Gallus gallus":"chickens",
"Gambusia holbrooki":"fish",
"Gasterosteus aculeatus":"fish",
"Gerbillinae":"gerbil ",
"Girardinichthys viviparus":"fish",
"Gobiocypris rarus":"fish",
"Gobius niger":"fish",
"Gymnogyps californianus":"condors",
"Gyps fulvus":"vultures",
"Haemonchus contortus":"worms",
"Halichoerus grypus":"seals",
"Haliotis diversicolor supertexta":"clams",
"Harmonia axyridis":"Beetles",
"Hediste diversicolor":"worms",
"Helicoverpa armigera":"moths",
"Helix aspersa":"snails",
"Hemicentrotus pulcherrimus":"sea urchins",
"Herpestes javanicus":"mongoose",
"Heteropneustes fossilis":"fish",
"Heterotremata":"crabs",
"Hexaplex trunculus":"sea snail",
"Homarus americanus":"lobsters",
"Homo Sapien":"Humans",
"Hoplias malabaricus":"fish",
"Huso huso":"fish",
"Hyalella Azteca":"shrimp",
"Hyas araneus":"crabs",
"Hydra vulgaris":"polyps",
"Hynobius leechii":"salamanders",
"Hypentelium nigricans":"fish",
"Hypomesus transpacificus":"fish",
"Hypophthalmichthys molitrix":"fish",
"Hypophthalmichthys nobilis":"fish",
"Hypostomus commersoni":"fish",
"Hyriopsis cumingii":"clams",
"Ictalurus punctatus":"fish",
"Ixodes scapularis":"ticks",
"Isonychia":"insects",
"Jaculus orientalis":"rodents",
"Jenynsia multidentata":"fish",
"Kryptolebias marmoratus":"fish",
"Labeo":"fish",
"Labeo rohita":"fish",
"Laeonereis acuta":"fish",
"Lagenorhynchus acutus":"dolphins",
"Lampetra fluviatilis":"fish",
"Larus argentatus":"Birds",
"Lates calcarifer":"fish",
"Lepeophtheirus salmonis":"louse",
"Lepomis macrochirus":"fish",
"Lepomis megalotis":"fish",
"Leporinus obtusidens":"fish",
"Leuciscus idus":"fish",
"Leucoraja erinacea":"fish",
"Lithognathus mormyrus":"fish",
"Litopenaeus vannamei":"shrimp",
"Liza aurata":"Fish",
"Locusta migratoria":"Grasshopper",
"Lonchura malabarica":"birds",
"Lucilia cuprina":"insects",
"Lucilia sericata":"flies",
"Lumbriculus variegatus":"Worms",
"Lumbricus rubellus":"earthworms",
"Lumbricus terrestris":"earthworms",
"Lymnaea stagnalis":"snails",
"Lytechinus anamesus":"sea urchins",
"Macaca":"monkeys",
"Macaca fascicularis":"monkeys",
"Macaca mulatta":"monkeys",
"Macaca radiata":"monkeys",
"Macoma nasuta":"clams",
"Macrobrachium asperulum":"shrimp",
"Mactra quadrangularis":"clams",
"Mamestra brassicae":"moths",
"Manduca sexta":"hornworms",
"Marmosets":"monkeys",
"Melanotaenia fluviatilis":"fish",
"Meleagris gallopavo":"turkey",
"Menidia beryllina":"fish",
"Meriones unguiculatus":"gerbils",
"Mesocricetus auratus":"hamsters",
"Metapenaeus":"prawns",
"Metaphire posthuma":"Worms",
"Microgadus tomcod":"fish",
"Micropogonias undulatus":"fish",
"Micropterus dolomieu":"fish",
"Micropterus salmoides":"fish",
"Microtus agrestis":"voles",
"Microtus ochrogaster":"voles",
"Microtus oeconomus":"voles",
"Microtus pinetorum":"voles",
"Mizuhopecten yessoensis":"scallop",
"Monopterus albus":"eels",
"Montastraea franksi":"corals",
"Morone Americana":"fish",
"Mugil cephalus":"fish",
"Murinae":"rodents",
"Musca domestica":"Flies",
"Mus musculus":"Mice",
"Mustela":"weasels",
"Mustela putorius furo":"ferrets",
"Mya arenaria":"clams",
"Myodes glareolus":"voles",
"Mystus vittatus":"fish",
"Mytilus edulis":"mussels ",
"Mytilus galloprovincialis":"mussels",
"Mytilus trossulus":"mussels",
"Myzus persicae":"aphids",
"Nannopterum auritus":"birds",
"Nannospalax judaei":"rats",
"Neohelice granulate":"crabs",
"Neotoma lepida":"rats",
"Neovison vison":"rodents",
"Nilaparvata lugens":"planthoppers",
"Nippostrongylus brasiliensis":"roundworms",
"Nucella lapillus":"snails",
"Ochotona curzoniae":"rodents",
"Octopus vulgaris":"octopus",
"Odontophoridae":"birds",
"Oikopleura dioica":"tunicates",
"Onchocerca volvulus":"nematodes",
"Oncorhynchus clarkii henshawi":"fish",
"Oncorhynchus gilae apache":"fish",
"Oncorhynchus kisutch":"fish",
"Oncorhynchus mykiss":"fish",
"Oncorhynchus mykiss gairdneri":"fish",
"Oncorhynchus tshawytscha":"fish",
"Onychostoma barbatulum":"fish",
"Orchesella cincta":"insects",
"Oreochromis mossambicus":"fish",
"Oreochromis niloticus":"fish",
"Oryctolagus cuniculus":"rabbits",
"Oryzias":"fish",
"Oryzias javanicus":"fish",
"Oryzias latipes":"fish",
"Oryzias melastigma":"fish",
"Oryziinae":"fish",
"Ovis aries":"sheep",
"Oxya chinensis":"grasshoppers",
"Pagrus major":"fish",
"Palaemon elegans":"prawns",
"Palaemon pugio":"shrimp",
"Pan troglodytes":"chimpanzees",
"Papio":"monkeys",
"Papio Anubis":"monkeys",
"Papio ursinus":"monkeys",
"Paracentrotus lividus":"sea urchins",
"Paralichthys olivaceus":"sea urchins",
"Parascaris equorum":"roundworms ",
"Pardosa lugubris":"spiders",
"Parus major":"birds",
"Pediculus humanus":"lice",
"Pelophylax esculentus":"frogs",
"Pelophylax ridibundus":"frogs",
"Perca flavescens":"fish",
"Perca fluviatilis":"fish",
"Perinereis nuntia":"worms",
"Periplaneta Americana":"cockroaches",
"Perna viridis":"mussels",
"Peromyscus leucopus":"rodents",
"Petromyzon marinus":"fish",
"Phalacrocorax carbo":"birds",
"Phalangeridae":"marsupials",
"Phasianidae":"birds",
"Phasianus colchicus":"birds",
"Phlebotomus papatasi":"flies",
"Phoca largha":"seals",
"Phoca vitulina":"seals",
"Phodopus sungorus":"hamsters",
"Physella acuta":"snails",
"Physeter catodon":"whales",
"Physeteridae":"whale",
"Piaractus mesopotamicus":"fish",
"Pimephales promelas":"fish",
"Platichthys flesus":"fish",
"Plecoglossus altivelis":"fish",
"Pleurodeles waltl":"newts",
"Pleuronectes platessa":"fish",
"Plutella xylostella":"moths",
"Podarcis siculus":"lizards",
"Poecilia reticulata":"fish",
"Poecilia vivipara":"fish",
"Poeciliopsis lucida":"fish",
"Polypheretima elongata":"earthworms",
"Polypterus senegalus":"fish",
"Pomatoschistus microps":"fish",
"Porcellio dilatatus":"louse",
"Porcellio scaber":"louse",
"Prochilodus lineatus":"fish",
"Proechimys guyannensis":"rats",
"Pseudodiaptomus annandalei":"fish",
"Pseudopleuronectes americanus":"fish",
"Pusa hispida":"seals",
"Pusa sibirica":"seals",
"Pygoscelis adeliae":"penguins",
"Rajiformes":"fish",
"Rana catesbeiana":"frogs",
"Rana pipiens":"frogs",
"Rana sylvatica":"frogs",
"Rana temporaria":"frogs",
"Rangifer tarandus":"reindeer",
"Rattus norvegicus":"Rats",
"Rhinella marina":"toads",
"Rhipicephalus microplus":"ticks",
"Ruditapes decussatus":"clams",
"Ruditapes philippinarum":"clams",
"Rutilus rutilus":"fish",
"Saccostrea cucullata":"oysters",
"Saccostrea glomerata":"oysters",
"Saimiri sciureus":"monkeys",
"Salmo salar":"fish",
"Salmo trutta":"fish",
"Salvelinus alpinus":"fish",
"Sander lucioperca":"fish",
"Sapajus apella":"monkeys",
"Sarotherodon melanotheron":"fish",
"Scarus ghobban":"fish",
"Schistosoma bovis":"worms",
"Scophthalmus maximus":"fish",
"Scrobicularia plana":"mollusks",
"Scylla serrata":"crabs",
"Sebastes schlegelii":"fish",
"Sebastiscus marmoratus":"fish",
"Sepia officinalis":"cuttlefish",
"Seriola lalandi":"fish",
"Sesamia nonagrioides":"insects",
"Setaria cervi":"roundworms",
"Siganus canaliculatus":"fish",
"Siganus sutor":"fish",
"Sigmodon hispidus":"rats",
"Sinopotamon honanense":"crabs",
"Solea senegalensis":"fish",
"Solen grandis":"mollusks",
"Sparidae":"fish",
"Sparus aurata":"fish",
"Sphaerechinus granularis":"sea urchins",
"Spodoptera exigua":"moths",
"Spodoptera frugiperda":"moths",
"Squalius cephalus":"fish",
"Squalus acanthias":"fish",
"Sterna hirundo":"birds",
"Strongylocentrotus purpuratus":"sea urchins",
"Struthio camelus":"birds",
"Sturnus vulgaris":"bird",
"Sus scrofa":"boars",
"Sus scrofa domesticus":"pigs",
"Syncerus":"cows",
"Tachysurus fulvidraco":"fish",
"Taenia solium":"tapeworm",
"Taeniopygia guttata":"birds",
"Takifugu obscuru":"fish",
"Takifugu rubripes":"fish",
"Teleostei":"teleost fish",
"Tenebrio molitor":"insects",
"Testudo graeca nabeulensis":"tortoises",
"Tetranychus urticae":"mites",
"Tetraodon":"fish",
"Tetronarce californica":"stingrays",
"Thalassoma bifasciatum":"fish",
"Thalassoma pavo":"fish",
"Thunnus maccoyii":"fish",
"Tigriopus japonicas":"crustacean",
"Tor putitora":"fish",
"Torpedo marmorata":"stingray",
"Trachemys scripta":"turtles",
"Trematomus bernacchii":"fish",
"Tribolium castaneum":"beetles",
"Tribolium confusum":"beetles",
"Trichinella nativa":"nematodes",
"Trichinella pseudospiralis":"worms",
"Trichoplusia ni":"insects",
"Tubifex tubifex":"worms",
"Tursiops truncatus":"dolphins",
"Uca pugilator":"crabs",
"Ursus maritimus":"bears",
"Vespula maculifrons":"Flies",
"Xenopodinae":"frogs",
"Xenopus laevis":"frogs",
"Xenopus tropicalis":"frogs",
"Xeropicta derbentina":"snails",
"Xyrauchen texanus":"fish",
}